# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software.ui'
#
# Created: Tue Jan 12 02:08:09 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -406, 368, 795))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_2 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_1 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.verticalLayout_2.addWidget(self.checkBox_1)
        self.checkBox_11 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_3 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_10 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_9 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_8 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_7 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_6 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_5 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_15 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.verticalLayout_2.addWidget(self.checkBox_15)
        self.checkBox_19 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.verticalLayout_2.addWidget(self.checkBox_19)
        self.checkBox_16 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.verticalLayout_2.addWidget(self.checkBox_16)
        self.checkBox_14 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_18 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.verticalLayout_2.addWidget(self.checkBox_18)
        self.checkBox_17 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.verticalLayout_2.addWidget(self.checkBox_17)
        self.checkBox_13 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_29 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_29.setChecked(True)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.verticalLayout_2.addWidget(self.checkBox_29)
        self.checkBox_20 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.verticalLayout_2.addWidget(self.checkBox_20)
        self.checkBox_21 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.verticalLayout_2.addWidget(self.checkBox_21)
        self.checkBox_22 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.verticalLayout_2.addWidget(self.checkBox_22)
        self.checkBox_23 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_23.setChecked(False)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.verticalLayout_2.addWidget(self.checkBox_23)
        self.checkBox_24 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.verticalLayout_2.addWidget(self.checkBox_24)
        self.checkBox_25 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.verticalLayout_2.addWidget(self.checkBox_25)
        self.checkBox_26 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.verticalLayout_2.addWidget(self.checkBox_26)
        self.checkBox_27 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_27.setChecked(True)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.verticalLayout_2.addWidget(self.checkBox_27)
        self.checkBox_28 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.verticalLayout_2.addWidget(self.checkBox_28)
        self.checkBox_12 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Better Ubuntu - Software", None))
        self.checkBox_2.setText(_translate("Dialog", "chromium-browser", None))
        self.checkBox_1.setText(_translate("Dialog", "cinnamon", None))
        self.checkBox_11.setText(_translate("Dialog", "cmake", None))
        self.checkBox_3.setText(_translate("Dialog", "gimp", None))
        self.checkBox_4.setText(_translate("Dialog", "git", None))
        self.checkBox_10.setText(_translate("Dialog", "gnome-tweak-tool", None))
        self.checkBox_9.setText(_translate("Dialog", "htop", None))
        self.checkBox_8.setText(_translate("Dialog", "ipython", None))
        self.checkBox_7.setText(_translate("Dialog", "josm", None))
        self.checkBox_6.setText(_translate("Dialog", "keepass2", None))
        self.checkBox_5.setText(_translate("Dialog", "ninja-ide", None))
        self.checkBox_15.setText(_translate("Dialog", "numix-gtk-theme", None))
        self.checkBox_19.setText(_translate("Dialog", "numix-icon-theme-circle", None))
        self.checkBox_16.setText(_translate("Dialog", "numix-wallpaper-*", None))
        self.checkBox_14.setText(_translate("Dialog", "openssh-server", None))
        self.checkBox_18.setText(_translate("Dialog", "python-pip", None))
        self.checkBox_17.setText(_translate("Dialog", "python-pyglet", None))
        self.checkBox_13.setText(_translate("Dialog", "python-wxgtk2.8", None))
        self.checkBox_29.setText(_translate("Dialog", "pyqt4-dev-tools", None))
        self.checkBox_20.setText(_translate("Dialog", "qtcreator", None))
        self.checkBox_21.setText(_translate("Dialog", "qt4-designer", None))
        self.checkBox_22.setText(_translate("Dialog", "sl", None))
        self.checkBox_23.setText(_translate("Dialog", "spotify-client", None))
        self.checkBox_24.setText(_translate("Dialog", "steam", None))
        self.checkBox_25.setText(_translate("Dialog", "texmaker", None))
        self.checkBox_26.setText(_translate("Dialog", "tmux", None))
        self.checkBox_27.setText(_translate("Dialog", "unity-tweak-tool", None))
        self.checkBox_28.setText(_translate("Dialog", "virtualbox", None))
        self.checkBox_12.setText(_translate("Dialog", "vlc", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

